### ISSUE TITLE
How to run ./build.sh

### ISSUE THREAD

**Issue by thuc248997** [lexra/userboard-rzv2m#1]
`umount: mnt: not mounted`
when run `./build.sh`, i have a issue.

**Comment by lexra** [comment]
... || true
we don't care if that fails.

**Comment by lexra** [comment]
> `umount: mnt: not mounted` when run `./build.sh`, i have a issue.

... || true
we don't care if that fails.

**Comment by thuc248997** [comment]
Many thanks! Can you give me your contact so I can contact you faster?

**Comment by lexra** [comment]
Download from Renesas official website and place the followings to the proprietary folder: 
    core1_firmware.bin
    r11an0530ej0500-rzv2m-drpai-sp.zip
    rzv2m_drpai-sample-application_ver5.00.tar.gz
    rzv2m_meta-drpai_ver5.00.tar.gz
    DRP-AI_Translator-v1.60-Linux-x86_64-Install
    rzv2m_ai-implementation-guide_ver5.00.tar.gz
    rzv2m_isp_support-pkg_v110.tar.gz
